name: render-deploy-pt21a-backend

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Versión más estable y ampliamente utilizada

      ## Upload to DockerHub

      - name: Set up docker Build
        uses: docker/setup-buildx-action@v1  # Versión estable v1

      - name: Log in to docker hub
        uses: docker/login-action@v1  # Versión estable v1
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push docker image
        uses: docker/build-push-action@v2  # Versión v2 más estable
        with:
          context: .
          file: ./ecommerce-gi4ncarlo/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-backend-pt21a:1.0

      ## Deploy to Render

      - name: Deploy to render
        uses: johnbeynon/render-deploy-action@v0.0.8  # La versión anterior más estable
        with: 
          service-id: ${{secrets.RENDER_SERVICE_ID}}
          api-key: ${{secrets.RENDER_API_KEY}}
          wait-for-success: true

    
